### ISSUE TITLE
Option to indent more?

### ISSUE THREAD

**Issue by bobrocke** [scriptin/brackets-indent-softwraps#10]
This is a very nice addition to Brackets. Would it be possible to make it just a little better by allowing a preference to indent something more than the line above? For me, I'd like it to be one space more, but others may like even deeper indents.

**Comment by scriptin** [comment]
It is possible by [adjusting `padding-left`](https://github.com/scriptin/brackets-indent-softwraps/blob/7c06309f548bce1432aeb2a36f93fa6957f3a8c1/main.js#L23).

You are the only person I know using this feature, and most of code editors I've seen don't have it, even though soft-wrap indentation is pretty common. Just found it in Android Studio, but it's very weird: lines are not even aligned properly after wrapping. I also don't have much time now, so I won't implement it.

Since this extension is not likely to change in the near future, you may just modify the line I've linked to in your copy. I guess this would do the trick:

```
paddingLeft = (noGutter ? DEFAULT_GUTTER_WIDTH : 0) + (offset + cm.defaultCharWidth()) + "px";
```

Or you may fork the repo and do it properly. I'm not familiar with Brackets API enough, so it's up to you.

**Comment by bobrocke** [comment]
How about an indent to the next indent level, rather than no indent at all?

**Comment by scriptin** [comment]
Extra indentation with one space makes it hard for me to read JS code, which often is indented by 2 spaces. Extra indentation with one more indentation level is even worse, because it makes me think that wrapped part is actually indented (like there is a hard wrap). That's why I find this feature somewhat confusing when editing code and that's why I think it is available/used quite rarely.

Of course, it's a matter of taste, I'm not saying it is bad to have such a feature, I just don't have enough time to read on API docs, implement and test it.

**Comment by bobrocke** [comment]
That makes sense. Let me work this way for a while and see if I end up actually preferring no indent!
