### ISSUE TITLE
Installation failed. The package.json is not valid (error was: SyntaxError: Unexpected token ).

### ISSUE THREAD

**Issue by OKNoah** [scriptin/brackets-indent-softwraps#2]
Got this error when installing from github's `.zip` by pasting in package manager GUI.

![screen shot 2015-01-29 at 1 59 43 pm](https://cloud.githubusercontent.com/assets/3739277/5967148/221b1010-a7bf-11e4-96fc-f0fb60625df8.png)

**Comment by scriptin** [comment]
Which version of brackets? Worked for me on 0.43.0

I think it's either a bug in parser, or I'm missing something about `package.json` format. I followed [instructions](https://github.com/adobe/brackets/wiki/Extension-package-format#packagejson-format) pretty rigorously, and the error is kinda strange - "Unexpected token <SHOULD BE SOMETHING HERE>". This is exactly why I couldn't add it to extension registry.

I'll take a closer look.

**Comment by OKNoah** [comment]
Thanks.

Version info:

Release 1.1 build 1.1.0-15558 (release ea908cae5) 
build timestamp: Wed Dec 17 2014 12:50:55 GMT-0800

**Comment by peterflynn** [comment]
It looks like the problem is that the package.json file contains a byte order marker (BOM).  I seems the ZIP decompressor that Brackets uses may do something funny with it (converting it to `0xFEFF`, a _UTF-16_ BOM which gets interpreted as a zero-width non-breaking space character -- hence the blank space in the error message), and in turn `JSON.parse()` chokes on that bad char.

Sounds exactly like this problem: http://stackoverflow.com/questions/7297888/ufeff-character-showing-up-in-files-how-to-remove-them

Since a BOM is unnecessary and not recommended for UTF-8 files anyway, the best solution is to edit your package.json file to remove it.  The Stackoverflow link above gives a bunch of tips on how to do that.  I'll make sure Brackets is tracking the unzip bug on our end as a general issue.

**Comment by scriptin** [comment]
@peterflynn Thanks, that helped!
